### ISSUE TITLE
package ‘supreme’ is not available (for R version 4.0.0)

### ISSUE THREAD

**Issue by sk-sahu** [strboul/supreme#8]
I'm trying to install this package from CRAN in R version 4.0.0

I guess all the packages in CRAN auto-build for this latest version of R. Isn't that the case?

Currently, I'm able to install from Github link `devtools::install_github("strboul/supreme")`

**Comment by strboul** [comment]
*supreme* hasn't made its journey to CRAN yet. The README is incorrect but I hope it'll be one day.
